parabox_packages <- c("base64enc"
                    ,"futile.logger"
                    ,"jsonlite"
                    ,"lazyeval"         
                    ,"plyr"         
                    ,"dplyr"
                    ,"RPostgreSQL"
                    ,"httr"
                    ,"igraph"
                    )