parabox_packages <- c("RPostgreSQL"
                    ,"base64enc"
                    ,"futile.logger"
                    ,"jsonlite"
                    ,"lazyeval"     
                    ,"lubridate"                
                    ,"devtools"  
                    ,"reshape2"     
                    ,"plyr"         
                    ,"dplyr"
                    ,"aws.s3"                                    
                    ,"text2vec"     
                    ,"tm"           
                    ,"randomForest" 
                    ,"glmnet"
                    , "stm"
                    )